import 'package:flutter/material.dart';

const Color signinTheamColor1 = Color(0xff7d4bff);
const Color signinTheamColor2 = Color(0xffc40df8);
const Color baseBlack = Color(0xff000000);
const Color logoWhite = Color(0xffffffff);
const Color icongray = Color(0xffb1bcc5);
const Color bottumnavigationWhite = Color(0xffffffff);
const Color dashAppBarColor = Color(0xffecedf1);
const Color dashAppBarItemColor = Color(0xff475b65);
const Color dashHeaderItemColor = Color(0xff475b65);
const Color dashHeaderSubItemColor = Color(0xff768e9a);
const Color dashTileColor = Color(0xfffffefe);
const Color selectedItemColor = Color(0xff36464e);
const Color gridBorderColor = Color(0xffF6F6F6);
const Color gridHeaderColor = Color(0xffE2F6F8);
const Color tableHeadereColor = Color(0xff263238);
const Color complaintTailDateTimeColor = Color(0xff575757);
const Color searchBoxItemsColor = Color(0xffffffff);
const Color tableHeaderbgColor = Color.fromARGB(255, 232, 216, 236);
